# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 19:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='general',
            name='serie',
            field=models.ForeignKey(default=777, on_delete=django.db.models.deletion.CASCADE, to='reviews.Serie'),
        ),
    ]
