# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20160505_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='general',
            name='calificacion',
        ),
        migrations.AddField(
            model_name='general',
            name='calificacion1',
            field=models.IntegerField(default=777),
        ),
        migrations.AddField(
            model_name='general',
            name='calificacion2',
            field=models.IntegerField(default=777),
        ),
        migrations.AddField(
            model_name='general',
            name='calificacion3',
            field=models.IntegerField(default=777),
        ),
        migrations.AddField(
            model_name='general',
            name='calificacion4',
            field=models.IntegerField(default=777),
        ),
        migrations.AddField(
            model_name='general',
            name='calificacion5',
            field=models.IntegerField(default=777),
        ),
        migrations.AddField(
            model_name='general',
            name='calificacionP',
            field=models.IntegerField(default=777),
        ),
    ]
