# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20160505_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='general',
            name='foto',
            field=models.ImageField(upload_to='assets/images'),
        ),
        migrations.AlterField(
            model_name='general',
            name='trailer',
            field=models.FileField(upload_to='assets/videos'),
        ),
    ]
